"""empty message

Revision ID: 7cdfe2d4f328
Revises: 5409c24fd08e
Create Date: 2019-04-15 13:06:21.520423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdfe2d4f328'
down_revision = '5409c24fd08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_country_code_fkey', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'country', ['country_code'], ['country_code'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_country_code_fkey', 'city', 'country', ['country_code'], ['country_code'])
    # ### end Alembic commands ###
