"""empty message

Revision ID: b7ae48ffc462
Revises: 398de4f723c4
Create Date: 2019-04-12 09:40:27.775652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ae48ffc462'
down_revision = '398de4f723c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('percentage_of_use', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'CountryLanguage', 'language', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CountryLanguage', type_='foreignkey')
    op.drop_table('language')
    # ### end Alembic commands ###
